### ISSUE TITLE
Aurora 35.0a2 incompatible with the addon.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat-reporter-extensions#10]
0. Go to addons site with Firefox Android Aurora 35.0a2
1. Click on webcompat

The addon is not installed. 
It says that Firefox 35.0a2 is not compatible.

**Comment by miketaylr** [comment]
Hmm, sorry that I missed this. Will investigate soon.

**Comment by miketaylr** [comment]
I think we can close this now -- we're working on a fix w/ the WebExtension version https://github.com/webcompat/webcompat-reporter-extensions/commit/5bfa4bd8c34aa26a244d09f8697c4ceb236ff228 (just waiting on a bugfix on the Gecko side, currently blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1254003 unless we want to try a `setTimeout` workaround)
