### ISSUE TITLE
Remove empty dependencies key from package.json

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#100]
https://github.com/webcompat/webcompat-reporter-extensions/blob/master/package.json#L43

**Comment by OrionStar25** [comment]
I don't see any empty dependency keys in that file :O

**Comment by miketaylr** [comment]
See line 43? `"dependencies": {}`

We can delete that, since it's not doing anything.

**Comment by OrionStar25** [comment]
Oh! I thought you meant develop dependencies. Shall do so ASAP.
