### ISSUE TITLE
npm run firefox throwing error

### ISSUE THREAD

**Issue by deeptibaghel** [webcompat/webcompat-reporter-extensions#105]
deeptibaghel@MacBook-Pro:~/webcompat-reporter-extensions$ npm run firefox

> webcompat-reporter-addon@0.5.1 firefox /Users/deeptibaghel/webcompat-reporter-extensions
> web-ext run --source-dir=dist/firefox

Running web extension from /Users/deeptibaghel/webcompat-reporter-extensions/dist/firefox

Error: getaddrinfo ENOTFOUND localhost localhost:6005
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

Error code: ENOTFOUND

npm ERR! Darwin 17.4.0
npm ERR! argv "/usr/local/Cellar/node@6/6.13.0/bin/node" "/usr/local/bin/npm" "run" "firefox"
npm ERR! node v6.13.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! webcompat-reporter-addon@0.5.1 firefox: `web-ext run --source-dir=dist/firefox`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webcompat-reporter-addon@0.5.1 firefox script 'web-ext run --source-dir=dist/firefox'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webcompat-reporter-addon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     web-ext run --source-dir=dist/firefox
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webcompat-reporter-addon
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webcompat-reporter-addon
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/deeptibaghel/webcompat-reporter-extensions/npm-debug.log

**Comment by miketaylr** [comment]
See also https://github.com/mozilla/web-ext/issues/1083

**Comment by OrionStar25** [comment]
I suggest upgrade your npm and install `web-ext`.

**Comment by miketaylr** [comment]
This is working for me now.
