### ISSUE TITLE
Don't allow double install in Firefox or Firefox for Android

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#11]
For Fennec Nightly users, installing the addon shouldn't add another menu item.

See https://github.com/webcompat/webcompat.com/issues/825.

**Comment by AkhilHector** [comment]
@miketaylr I will take up this issue, I faced the same issue when i created a report option in context menu. Every time i test i used to have the context menu being declared twice.

**Comment by miketaylr** [comment]
> For Fennec Nightly users, installing the addon shouldn't add another menu item.

One thing to keep in mind is this "add-on" exists natively in Firefox for Android (for Aurora and Nightly): https://dxr.mozilla.org/mozilla-central/source/mobile/android/chrome/content/WebcompatReporter.js

So the idea is to prevent installation of the AMO add-on on Nightly and Aurora channels.

We hope to have something similar for Firefox desktop very soon as well.

**Comment by rugk** [comment]
Mhh see https://github.com/webcompat/web-bugs/issues/14191

What is the current state? Nothing works in Firefox 57 for Android.

**Comment by miketaylr** [comment]
> What is the current state? Nothing works in Firefox 57 for Android.

That's a bug. I need to take a look at 57 compat, ideally we have an add-on option for stable users.

**Comment by miketaylr** [comment]
Oops, that's a different issue. I'll file a new one.
