### ISSUE TITLE
Investigate if firefox-mobile can be using the shared manifest.json

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#120]
I totally don't remember if it's using it's own manifest.json is on purpose, or just something I forgot to do. 

If it's possible, we should use the shared one. If not, we should leave a comment somewhere (maybe in the webpack config file).

**Comment by laghee** [comment]
So... in the process of testing whether it would work to use the shared manifest basically as is, I've stumbled upon another potential problem. After encountering errors with the shared manifest version of the mobile extension, I find I can't even get the **original** extension to load on either Android 7.0 or 8.0 (at least not as an unsigned zip file, [as laid out here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Developing_WebExtensions_for_Firefox_for_Android)).

I get a lovely pop-up error (the same one I get with the altered webpack config version) instead: 

![screenshot_20180522-143004](https://user-images.githubusercontent.com/20972610/40363385-a71dfc90-5dcf-11e8-8022-d2e9a1f9df7b.jpg)

When I run it through Mozilla's add-on validator (which, I'm not sure, may not make sense for mobile?), it insists that the manifest.json has block comments that need to be removed:

![screenshot 2018-05-22 14 49 27](https://user-images.githubusercontent.com/20972610/40363280-5eee224c-5dcf-11e8-8d23-c675eebd3123.png)

Needless to say ... actually no block comments.

Not sure what's going on here, but I'll check the desktop Firefox extension as long as I'm at it.

**Comment by miketaylr** [comment]
Thanks for digging into this!
