### ISSUE TITLE
The “Report Site Issue” extension icon is smaller on Chrome than on Firefox

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#128]
Originally filed @ https://github.com/webcompat/webcompat.com/issues/2541 by @softvision-sergiulogigan.

@laghee, can you investigate?

**Comment by laghee** [comment]
@miketaylr So it looks like we simply haven't uploaded (or whatever it is one does to release) the updated v0.5.1 to the Chrome web store. The icons were all updated in March, and the current version in the Chrome extension manifest is 0.5.1, but the actual extension available to download is ... 0.5.0 from early 2017:

<img width="918" alt="screenshot 2018-07-06 22 34 51" src="https://user-images.githubusercontent.com/20972610/42399311-9efd4de2-816d-11e8-9900-264f7e59cf6f.png">

**Comment by miketaylr** [comment]
Whoops. Thanks for checking that out.

Do you think we should update the icons to match the current dark ones? Or just leave it as-is?

**Comment by laghee** [comment]
Hmmm. Personally, I don't ❤️  the new ones at that size. The webcompat.com one is more visible but looks a little pixel-y 
<img width="32" alt="screenshot 2018-07-06 22 49 24" src="https://user-images.githubusercontent.com/20972610/42399687-263b0a46-816f-11e8-9ddb-0b7e0665d105.png">
 and the super-high-def-vector one  @magsout gave me to render for metrics-client is really hard to see: 
<img width="29" alt="screenshot 2018-07-06 22 52 07" src="https://user-images.githubusercontent.com/20972610/42399723-41c2146c-816f-11e8-9f71-77a5200c37a3.png">

I think the current one actually looks pretty good: 
<img width="33" alt="screenshot 2018-07-06 22 49 30" src="https://user-images.githubusercontent.com/20972610/42399757-5add2e32-816f-11e8-9ba9-6fdc424dfc6b.png">

But it wouldn't be hard to update them if I'm in the minority opinion (particularly using that nifty favicon-webpack-addon thing).

**Comment by miketaylr** [comment]
It's OK, no need to create extra work for something so low priority. Let me see if I can get that Chrome update published...

**Comment by miketaylr** [comment]
@laghee I ran into https://github.com/webcompat/webcompat-reporter-extensions/issues/129 trying to publish a new version. Any ideas?

**Comment by miketaylr** [comment]
I've just published the latest version, this should be fixed now: https://chrome.google.com/webstore/detail/ffnnhckjcpbbjlmgfjigknkoffakclol/publish-accepted?authuser=0&hl=en-US
