### ISSUE TITLE
typeerorr with chrome addon installed

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#131]
```
Uncaught TypeError: Cannot read property 'classList' of null
    at content.js:6
```

str:
1. install official webcompat reporter addon in chrome
2. visit webcompat.com and look in console

looks like maybe we need to update that selector (possibly for all addons?)

**Comment by laghee** [comment]
Yeah, weird, I don't get the same error in nightly, beta, or release, but it's definitely not hiding the download link in firefox (or fennec). 

DevEd console:
<img width="1167" alt="screenshot 2018-07-10 16 48 36" src="https://user-images.githubusercontent.com/20972610/42517926-30331ef4-8461-11e8-9af6-f5cd8bd46be4.png">

**Comment by miketaylr** [comment]
We probably just changed the classname of the link and forgot to update the content script here in the addon.

**Comment by laghee** [comment]
Yep, looks like it needs to be replaced with `body-webcompat`.

**Comment by laghee** [comment]
😂 oops. Yeah, I guess that makes more sense. I must have found `is-hidden` in there and gotten confused.

Is it better practice to drill down to the smallest possible element (e.g., not using the outer `js-addon` block)?

**Comment by miketaylr** [comment]
> Is it better practice to drill down to the smallest possible element (e.g., not using the outer js-addon block)?

As long as we hide the link that we need to, it probably doesn't matter that much.

**Comment by miketaylr** [comment]
![screen shot 2018-09-26 at 9 36 59 am](https://user-images.githubusercontent.com/67283/46087348-bd85e700-c16f-11e8-840c-9abf2cb12fb4.png)

**Comment by miketaylr** [comment]
Cool!

I believe the fix will be to update the selector in content.js, to match the the updated class name on webcompat.com:

```
<a class="nav-link js-addon-link" href="https://chrome.google.com/webstore/detail/webcompatcom-reporter/ffnnhckjcpbbjlmgfjigknkoffakclol" title="Navigate to Chrome webstore">
            <svg class="icon nav-icon" viewBox="0 0 30 30" role="presentation" aria-hidden="true">
                <use xlink:href="#svg-download2"></use>
            </svg>
            <span class="link-text">Download Chrome Add-on</span>
        </a>
```

To verify it's working locally, with Chrome, install your local addon, go to webcompat.com, and make sure there's no console errors, and also that the "Download Chrome Add-on" link is hidden.

**Comment by miketaylr** [comment]
We really need to get better at closing out fixed issues. 😓

**Comment by miketaylr** [comment]
(and publish an update to the chrome store)

**Comment by miketaylr** [comment]
Arf, not fixed yet. There's a PR.
