### ISSUE TITLE
npm run opera throwing error on windows

### ISSUE THREAD

**Issue by mbuotidem** [webcompat/webcompat-reporter-extensions#133]
C:\Users\Michael\webcompat-reporter-extensions>npm run opera
npm ERR! missing script: opera

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Michael\AppData\Roaming\npm-cache\_logs\2018-09-29T15_55_40_962Z-debug.log

[2018-09-29T15_55_40_962Z-debug.log](https://github.com/webcompat/webcompat-reporter-extensions/files/2430831/2018-09-29T15_55_40_962Z-debug.log)

**Comment by laghee** [comment]
@mbuotidem Yay! Thanks for the reports. This particular one I can explain -- while we have `run` scripts for Firefox and Chrome, we don't currently have one for Opera (which is why node can't find it).

Maybe writing one is something we might add as a `good next bug`... @miketaylr?
