### ISSUE TITLE
npm run chrome does not work on windows

### ISSUE THREAD

**Issue by mbuotidem** [webcompat/webcompat-reporter-extensions#134]
Trying to run the extension on chrome on windows almost works but then spouts the error : 

Failed to load extension from: C:\Program Files(x86)\Google\Chrome\Application\69.0.3497.100\dist\chrome. Manifest file is missing or unreadable.  

Clicking ok opens the chrome browser to the webcompat website. 

(As screenshot shows, firefox works but opera does not)

![operanorchrome](https://user-images.githubusercontent.com/4692052/46247890-929dcc00-c3d7-11e8-85b9-988d648c0bcf.PNG)

**Comment by laghee** [comment]
Ah, interesting. Looks to me like the way we're fetching the path to the extension in `chrome/run.js` doesn't work on Windows. There's probably a system-agnostic way to set that up.

**Comment by mbuotidem** [comment]
Thanks that fixed it.
