### ISSUE TITLE
[Regression] Reported sites on webcompat.com shows raw JSON data

### ISSUE THREAD

**Issue by reinhart1010** [webcompat/webcompat-reporter-extensions#139]
After pull #137 has been applied, the output of "Browser Configuration" shows raw JSON data instead of regular unordered list.

This one is from webcompat/web-bugs#19894.

> {u'mixed active content blocked': False, u'buildID': u'20181015220336', u'hasTouchScreen': False, u'tracking content blocked': u'false', u'consoleLog': [u'[JavaScript Warning: "Loading failed for the <script> with source https://cdn.jsdelivr.net/jquery/3.2.1/jquery.min.js." {file: "https://wj32.org/processhacker/nightly.php" line: 148}]', u'[JavaScript Warning: "Loading failed for the <script> with source https://cdn.jsdelivr.net/bootstrap/3.3.7/js/bootstrap.min.js." {file: "https://wj32.org/processhacker/nightly.php" line: 149}]', u'[JavaScript Warning: "Loading failed for the <script> with source https://maxcdn.bootstrapcdn.com/js/ie10-viewport-bug-workaround.js." {file: "https://wj32.org/processhacker/nightly.php" line: 150}]', u'[JavaScript Error: "ReferenceError: jQuery is not defined" {file: "https://wj32.org/processhacker/include/js/lightbox.min.js" line: 9}]\n@https://wj32.org/processhacker/include/js/lightbox.min.js:9:17\n@https://wj32.org/processhacker/include/js/lightbox.min.js:9:2\n'], u'gfx.webrender.blob-images': True, u'gfx.webrender.all': False, u'mixed passive content blocked': False, u'gfx.webrender.enabled': False, u'image.mem.shared': True, u'channel': u'aurora'}

**Comment by miketaylr** [comment]
I wonder if we fixed this...

**Comment by laghee** [comment]
Maybe this was related to https://github.com/webcompat/webcompat.com/issues/2653? At any rate, I don't see it happening with recent bot-reported issues (console log data, when included, still comes out as a unicode string -- https://github.com/webcompat/webcompat.com/issues/2659).

Closing as fixed for now.
