### ISSUE TITLE
Unable to report bug when submitted through addon

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat-reporter-extensions#20]
STR:
1) Load broken website
2) Click Webcompat addon site issue button
3) Fill in details about bug
4) Click Report via Github

Expected behavior:
Bug is filed, receive trophy.

Actual behavior:
Site hangs, spinner spins infinitely, reporter feels sadness within.

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by miketaylr** [comment]
Adam said to me on IRC that this works in Dev Edition, and not in Release. I think it's related to some FormData changes in 46+.

**Comment by miketaylr** [comment]
Hm, I wonder if this isn't a larger issue that isn't specific to the add-on.

I just did some ad-hoc testing and my findings were:

1) if you use the add-on and click "Report via GitHub" it fails. There's an error message about not having the right CORS headers, which is new. Something changed, possibly on GitHub's side of things. To investigate. See the screenshot here: https://irccloud.mozilla.com/file/uXqBVoCf/desktop.png
2) If you click "login" and do the auth dance, *then* use the add-on and click "Report via GitHub" it works.
3) If you click "logout" and then use the add-on and use "Report via GitHub" it works. That suggests that once you have a salted/hashed access token in the db you're OK.

So the next question: did we regress this, or did GitHub change something around OAuth/CORS? 💣 

@adamopenweb can you try Step 2 or Step 3? It sort of sucks to suggest you report invalid bugs to test... maybe we can sneak in a valid bug(that's a dupe, and we just dupe it so it looks less noisy 🙈.

**Comment by adamopenweb** [comment]
Mike,
I can confirm that step 2 works as expected https://webcompat.com/issues/2575.
Step 3 didn't work though, I got the mixed content blocking error again.

**Comment by miketaylr** [comment]
In theory this should be fixed now?

**Comment by adamopenweb** [comment]
WFM at the moment, let's close.

**Comment by miketaylr** [comment]
> at the moment

Such confidence!
