### ISSUE TITLE
Privacy section of README should mention screenshots

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat-reporter-extensions#21]
Since we're adding more functionality to those extensions I suppose the README could do with a bit of updating. Right now it says all that happens is submitting a URL to webcompat.com - it should mention screenshots.

**Comment by miketaylr** [comment]
That's a good idea @hallvors -- want to send a PR? https://webcompat.com/privacy mentions screenshots, could be some inspiration.

**Comment by miketaylr** [comment]
> want to send a PR? 

I'll take that as a no. 😄
