### ISSUE TITLE
 Can't submit compat bug in fennec

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#22]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1280650

Reported by @adamopenweb 

There isn't an option to say "Yes" when asked to report site issue.

STR:
1. Open Firefox Android 47
2. Navigate to a website (eg. web.skype.com)
3. Select "Request desktop site" 
4. Dialog appears asking if you would like to report a site issue

Expected results:
Option for Yes or No thanks

Actual results:
Only "No thanks" appears

**Comment by denschub** [comment]
Fun, I recently discovered the same issue somewhere else some time ago.
