### ISSUE TITLE
Add webcompat reporter to context menu in Firefox

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat-reporter-extensions#27]
As someone who looks into the errors on page, I often right-click and go to my Inspector/Dev Tools. The context menu would be a great spot to put a link to the webcompat form.

<img width="220" alt="context" src="https://cloud.githubusercontent.com/assets/6587558/18108904/97936618-6edc-11e6-800d-e265b4c7e803.png">

**Comment by miketaylr** [comment]
Yeah, this shouldn't be very hard -- we should do it for all add-ons (not just Firefox dekstop) if they provide the APIs.

**Comment by miketaylr** [comment]
Chrome, Opera, Firefox:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextMenus
https://developer.chrome.com/extensions/contextMenus

For Safari... https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/AddingContextualMenuItems/AddingContextualMenuItems.html

But I don't know if I want to keep maintaining it -- it costs $100 a year to be a developer and publish add-now. >:|

**Comment by AkhilHector** [comment]
I'm on it @miketaylr

**Comment by miketaylr** [comment]
Awesome @AkhilHector!

**Comment by miketaylr** [comment]
(updating title to be just for Firefox, will file issue for Chrome and Opera)
