### ISSUE TITLE
Use a shorter name when the icon is placed in the menu

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat-reporter-extensions#29]
In the menu, it might be better if to have a short name like "Report Issue" and hover text can have more detailed explanation.

<img width="168" alt="menu" src="https://cloud.githubusercontent.com/assets/6587558/18109103/7ecb1332-6edd-11e6-8ff4-48299a7898ac.png">

Here is an example:
<img width="267" alt="fullscreen" src="https://cloud.githubusercontent.com/assets/6587558/18109177/d2cdb3f4-6edd-11e6-84b3-cf1b562edaf7.png">

**Comment by miketaylr** [comment]
Yeah, I wanna see what "Report Site Issue" looks like. Seems about the same size as "New Private Window"

**Comment by AkhilHector** [comment]
@miketaylr you might want to have a look at this

![screenshot from 2016-09-02 22 17 38](https://cloud.githubusercontent.com/assets/5903056/18211420/1ee3b6f6-715b-11e6-9be2-ad995381ab76.png)

**Comment by miketaylr** [comment]
Seems good @AkhilHector -- I guess they use Title Case, so it should be `Report Site Issue`

**Comment by AkhilHector** [comment]
Cool should i submit a PR ?

**Comment by AkhilHector** [comment]
yeah that would actually clear a lot of confusion. +1 @miketaylr
