### ISSUE TITLE
Add context menu options for Chrome and Opera add-ons

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#31]
See https://github.com/webcompat/webcompat-reporter-extensions/issues/27.

The change should be perhaps literally the exact as https://github.com/webcompat/webcompat-reporter-extensions/pull/30.

**Comment by AkhilHector** [comment]
i will work on it @miketaylr

**Comment by miketaylr** [comment]
Fixed!

(one cool thing to do is if you make the title of the PR something like "Fixes #31: blah blah" when it gets merged it will automatically close the issue)
