### ISSUE TITLE
Add eslint linting

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#33]
We can probably just run this via npm scripts, so a package.json would be needed as well.

http://eslint.org/docs/user-guide/command-line-interface

We use the following settings for webcompat.com:

https://github.com/webcompat/webcompat.com/blob/master/package.json#L53

**Comment by AkhilHector** [comment]
i got this too @miketaylr

**Comment by miketaylr** [comment]
👍
