### ISSUE TITLE
Add-on should add a class to documentElement to hide "install our extension!" prompt

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#34]
cf. https://github.com/webcompat/webcompat.com/issues/1162

Not sure how the timing will work out, but if we can add a class like `has-extension` to `document.documentElement` we can make the page look less dumb.

**Comment by adamopenweb** [comment]
The extension will want to detect that it's on homepage of webcompat.com. Will need to use a content script and might want to use something like 'window.location.href' to get the current address.

**Comment by miketaylr** [comment]
I'll take this one.
