### ISSUE TITLE
Send custom headers when reporting via add-on

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#39]
`X-Requested-With` (or something)

(even though X- prefix is discouraged: https://tools.ietf.org/html/rfc6648 -- there's zero chance this header with become widely used....so whatever)

possible values: 

addon-firefox, addon-chrome, addon-opera, addon-fennec, 
native-firefox, native-fennec (for the versions that ship/will ship in Nightly/Aurora)

Do we bother including the browser version w/ the header? I'm leaning towards no because we can get that from the page already.

**Comment by miketaylr** [comment]
maybe addon-reporter-firefox & native-reporter-firefox are better. 🚲 🏠

**Comment by miketaylr** [comment]
<img width="545" alt="screen shot 2016-09-08 at 5 54 58 pm" src="https://cloud.githubusercontent.com/assets/67283/18369783/6c6bddc2-75ed-11e6-88ca-c596c7201b05.png">

**Comment by karlcow** [comment]
hehe.

> `X-Requested-With` (or something) […] there's zero chance this header with become widely used....so whatever)

`X-Requested-With` is used a lot in XHR cross domain requests ;) Probably a slip of mind.

I'm glad you used `X-Reported-With` on 
https://github.com/webcompat/webcompat-reporter-extensions/commit/6a2b39a3c495447cae2f32b9fd119d432e284517#diff-2e326533c87ec09a36dfc8b1cfb88367R35

**Comment by miketaylr** [comment]
> Probably a slip of mind.

😆
