### ISSUE TITLE
Add X-Reported-With headers to Chrome, Opera, and Firefox for Android add-ons

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#41]
Just like https://github.com/webcompat/webcompat-reporter-extensions/pull/40.

`var reporterID = 'addon-reporter-firefox';` should be different, though.

'addon-reporter-chrome', 'addon-reporter-opera', 'addon-reporter-fennec' seem good.

**Comment by AkhilHector** [comment]
Shall i @miketaylr ?

**Comment by miketaylr** [comment]
👍

**Comment by miketaylr** [comment]
I'm gonna push a fix to #43, check out those changes before submitting a PR @AkhilHector.

**Comment by AkhilHector** [comment]
Okay @miketaylr

**Comment by miketaylr** [comment]
(I'm gonna steal this one since I'm already updating a few things)

**Comment by miketaylr** [comment]
(but just for Chrome and Opera, need to open a new issue for Fennec)

**Comment by miketaylr** [comment]
(oh, and a random commit updating the firefox mobile build script)
