### ISSUE TITLE
Remove jpm and web-ext as dev dependencies for chrome and opera 

### ISSUE THREAD

**Issue by AkhilHector** [webcompat/webcompat-reporter-extensions#42]

**Comment by AkhilHector** [comment]
@miketaylr can i know the status ?

**Comment by miketaylr** [comment]
@AkhilHector sorry, didn't know there was a question. This is ready to be worked on -- those deps don't make any sense for chrome or opera.

**Comment by AkhilHector** [comment]
@miketaylr yep i know those deps don't make sense but you said you wanted to work on this issue, So i wanted to know when you will submit the PR, the status was about the PR. :P
PS :  I am more than happy to work on this if you are busy

**Comment by miketaylr** [comment]
@AkhilHector oh oops. Yep, go for it!

**Comment by AkhilHector** [comment]
+1
