### ISSUE TITLE
Add an npm top level command for running eslint on all add-on folders 

### ISSUE THREAD

**Issue by akhilpandey95** [webcompat/webcompat-reporter-extensions#45]
The command must eslint the following sub-folders : 
- `firefox`
- `chrome`
- `opera`

PS  : The command must run from the project root

**Comment by AkhilHector** [comment]
@miketaylr i want to close this so should i get this done once #52 is done or should i go ahead irrespective of that ?

**Comment by miketaylr** [comment]
@AkhilHector nah, go ahead. I can re-base the changes in #52 or fix any conflicts when it's ready!

**Comment by AkhilHector** [comment]
Ok

**Comment by miketaylr** [comment]
I moved to a global eslint command, so this isn't needed anymore.
