### ISSUE TITLE
Create SVG icon for reporter

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat-reporter-extensions#51]
As discussed we should switch our icon to SVG for the reporter.

**Comment by karlcow** [comment]
@adamopenweb http://www.la-grange.net/tmp/lightbulb.svg

**Comment by miketaylr** [comment]
<img width="360" alt="screen shot 2016-11-10 at 1 10 17 pm" src="https://cloud.githubusercontent.com/assets/67283/20190735/3f927c8e-a748-11e6-9f67-f5316fd78ccb.png">
<img width="203" alt="screen shot 2016-11-10 at 1 11 45 pm" src="https://cloud.githubusercontent.com/assets/67283/20190740/436944d2-a748-11e6-88cd-f0842db8ad56.png">

We can do some work to tweak how this appears in the toolbar vs the menu panel, but for now -- let's close. 💯
