### ISSUE TITLE
[bug] broken download link in Safari

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat-reporter-extensions#58]
Download link to the extension is broken in Safari.

<img width="1233" alt="screen shot 2017-01-03 at 8 24 47 pm" src="https://cloud.githubusercontent.com/assets/562354/21620044/b6589cfc-d1f2-11e6-8ac7-7ba26c4a1975.png">

**Comment by miketaylr** [comment]
We removed this link a while ago: https://github.com/webcompat/webcompat.com/issues/1140
