### ISSUE TITLE
Set up Travis lint task

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#65]
We don't have tests really... but we're going to have a nice linting task when #64 is merged. It would be cool to at least set up Travis to lint all PRs.

**Comment by AkhilHector** [comment]
Can i work on this ?

**Comment by miketaylr** [comment]
> We don't have tests really...

I just added tests in https://github.com/webcompat/webcompat-reporter-extensions/commit/745725c6d80812df17a2cdd2c0bebf8bc5775861, and travis runs eslint before running tests now:

https://github.com/webcompat/webcompat-reporter-extensions/commit/745725c6d80812df17a2cdd2c0bebf8bc5775861#diff-354f30a63fb0907d4ad57269548329e3R23
