### ISSUE TITLE
Add build ID if it's Firefox Nightly

### ISSUE THREAD

**Issue by MDTsai** [webcompat/webcompat-reporter-extensions#71]
With build ID, it's possible to reduce the time to find new regression.

**Comment by miketaylr** [comment]
Great idea! Can you file this bug in Web Compatibility Tools::General? We'll have to make the changes in m-c, since the web extensions version won't have access to this, I think.

(I can help out if you'd like to write the patches as well.)

**Comment by yfdyh000** [comment]
FYI: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/buildID

**Comment by yfdyh000** [comment]
I think this should be implemented with javascript on webpage.

https://github.com/webcompat/webcompat.com/blob/2fa22118e5c2b23c552214c127d99d002e1c6353/webcompat/form.py#L99 uses ua_header.

**Comment by yfdyh000** [comment]
In addition, os should get the build id too, like 15063 or more detail.

**Comment by miketaylr** [comment]
> I think this should be implemented with javascript on webpage.

I think so too -- let me file a bug for webcompat.com.

**Comment by miketaylr** [comment]
Let's close this in favor of https://github.com/webcompat/webcompat.com/issues/2047.
