### ISSUE TITLE
Write useful npm commands for building addons

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#75]
Right now I have to do `./node_modules/web-ext/bin/web-ext build`, and that tosses stuff in `./web-ext-artifacts`, but it should go in bin. Something like `npm run build` should do something smarter.

**Comment by zoepage** [comment]
To clarify, you refer to https://docs.npmjs.com/cli/build? Happy to send a PR.

**Comment by miketaylr** [comment]
> To clarify, you refer to https://docs.npmjs.com/cli/build? Happy to send a PR.

Maybe...? I've never used that before. Basically I want to have the output of the following command:

`./node_modules/web-ext/bin/web-ext build`

put things here:

https://github.com/webcompat/webcompat-reporter-extensions/tree/master/bin

But this probably isn't worth sending in a PR just yet, there's a few things that need to be cleaned up (mostly getting rid of the redundancies).

**Comment by miketaylr** [comment]
I'm fixing this in the PR for #74. Let's close here.
