### ISSUE TITLE
Pass tab.id when possible

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#85]
> Please pass an explicit tab.id when possible. Your current code is prone to a race condition, and in the worst case you would leak cross-origin data to other websites (because you are not passing the tabID of the new tab to chrome.tabs.executeScript).

**Comment by OrionStar25** [comment]
Hey, I'd like to work on this one!

**Comment by miketaylr** [comment]
Sounds good, thanks!

**Comment by OrionStar25** [comment]
I understand the issue, but it would be great if you could please tell me where I could start from. :sweat_smile:

**Comment by miketaylr** [comment]
Check out the following, @OrionStar25:

https://developer.chrome.com/extensions/tabs#method-executeScript
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/executeScript

We need to pass `tabId` into `executeScript`.

**Comment by miketaylr** [comment]
Note that in the latest code, we don't pass in the tab id to `reportIssue`:

https://github.com/webcompat/webcompat-reporter-extensions/blob/master/shared/base.js#L32

So we need to make sure it ends up there, so it will be in scope for the `executeScript` call (and that it's the *new* tab, not the existing tab.
