### ISSUE TITLE
Delete Safari add-on

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#86]
It's not maintained.

**Comment by Kagamihime** [comment]
I would like to take this issue, please

**Comment by miketaylr** [comment]
Oops, I haven't had enough caffeine yet. :)

@Kagamihime can you also delete the top-level `safari` directory, which contains the source files? You can send in a new PR for that, thanks!

**Comment by Kagamihime** [comment]
Of course, I will do that ;)
I was wondering about it

**Comment by miketaylr** [comment]
Great, thanks!

**Comment by miketaylr** [comment]
Oops, forgot to close this!
