### ISSUE TITLE
Add Intern unit tests for isReportableUrl

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#90]
https://github.com/webcompat/webcompat-reporter-extensions/blob/master/shared/base.js#L16

This will involve a little refactoring:

1. Pull out the isReportableURL into either its own module, or at least in the outer scope
2. Write a unit test that imports it
3. Make sure it gets run from the intern command (and passes!)

**Comment by ArushiSinghal** [comment]
Hi @miketaylr 
I want to work on this issue.

**Comment by miketaylr** [comment]
Great! Be sure to read https://github.com/webcompat/webcompat-reporter-extensions/blob/master/.github/CONTRIBUTING.md and post any questions you have here.

**Comment by OrionStar25** [comment]
If its still available for grabs I'd like to work on this please!

**Comment by miketaylr** [comment]
@ArushiSinghal are you still interested in working on this issue?
