### ISSUE TITLE
Create a `package:fennec` npm script command

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#93]
It should be possible to package the firefox for android addon by running the following command:

`npm run package:fennec`

(For a hint, take a look at the `package:firefox` script in package.json.)

**Comment by deeptibaghel** [comment]
@miketaylr I would like to take up this issue.

**Comment by miketaylr** [comment]
Great! Let me know if you have any questions.

**Comment by miketaylr** [comment]
Thanks @deeptibaghel!
