### ISSUE TITLE
Update npm dependencies

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#95]
You can install the following to see what's out of date and go from there!

https://www.npmjs.com/package/npm-check-updates

**Comment by laghee** [comment]
I'd like to work on this. The initial `ncu` report is:

 eslint                   4.16.0  →  4.18.1 
 eslint-config-prettier   ^1.7.0  →  ^2.9.0 
 prettier                 1.10.2  →  1.11.1 
 webpack                 ^3.10.0  →  ^4.0.1 

Should I go ahead and upgrade across the board, or are there issues with updating any of these?

Also, I noticed that when I `npm install`, I get several deprecated package warnings. Does ncu do anything about these, or are they handled another way?

**Comment by miketaylr** [comment]
Thanks for working on this @laghee!

I'd say if tests still pass after you update everything, we're good to go. The webpack major version bump is the only potentially tricky thing, but the tests explicitly cover webpack.

**Comment by miketaylr** [comment]
> Also, I noticed that when I npm install, I get several deprecated package warnings. Does ncu do anything about these, or are they handled another way?

Typically if the deprecated packages are dependencies of our top-level deps, it's OK to ignore this. We can't really control this, beyond filing bugs on those packages.

**Comment by laghee** [comment]
Thanks, @miketaylr. Tests still passed, so I've sent the PR.
