### ISSUE TITLE
Create a run chrome npm script command

### ISSUE THREAD

**Issue by ncarbon** [webcompat/webcompat-reporter-extensions#96]
There needs to be an npm script that runs the addon on Chrome on a command:

`npm run chrome`

**Comment by miketaylr** [comment]
This would be cool to have, though I have no idea if it's possible. Worth investigating.

**Comment by architajain12** [comment]
@miketaylr I'd like to work on this for my Outreachy contribution!

**Comment by miketaylr** [comment]
OK!
